# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.queryTermLE = QtWidgets.QLineEdit(self.groupBox)
        self.queryTermLE.setObjectName("queryTermLE")
        self.verticalLayout_2.addWidget(self.queryTermLE)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.queryServicesTW = QtWidgets.QTabWidget(self.groupBox_2)
        self.queryServicesTW.setObjectName("queryServicesTW")
        self.nominatimTab = QtWidgets.QWidget()
        self.nominatimTab.setObjectName("nominatimTab")
        self.gridLayout = QtWidgets.QGridLayout(self.nominatimTab)
        self.gridLayout.setObjectName("gridLayout")
        self.nominatimCountryCodeLE = QtWidgets.QLineEdit(self.nominatimTab)
        self.nominatimCountryCodeLE.setObjectName("nominatimCountryCodeLE")
        self.gridLayout.addWidget(self.nominatimCountryCodeLE, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.nominatimTab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.nominatimCountryCodeCB = QtWidgets.QCheckBox(self.nominatimTab)
        self.nominatimCountryCodeCB.setText("")
        self.nominatimCountryCodeCB.setObjectName("nominatimCountryCodeCB")
        self.gridLayout.addWidget(self.nominatimCountryCodeCB, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.nominatimTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.nominatimLimitLE = QtWidgets.QLineEdit(self.nominatimTab)
        self.nominatimLimitLE.setObjectName("nominatimLimitLE")
        self.gridLayout.addWidget(self.nominatimLimitLE, 1, 2, 1, 1)
        self.queryServicesTW.addTab(self.nominatimTab, "")
        self.geonamesTab = QtWidgets.QWidget()
        self.geonamesTab.setObjectName("geonamesTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.geonamesTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.geonamesTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.geonamesTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.geonamesUsernameLE = QtWidgets.QLineEdit(self.geonamesTab)
        self.geonamesUsernameLE.setObjectName("geonamesUsernameLE")
        self.gridLayout_2.addWidget(self.geonamesUsernameLE, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.geonamesTab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        self.geonamesFeatureClassCB = QtWidgets.QCheckBox(self.geonamesTab)
        self.geonamesFeatureClassCB.setText("")
        self.geonamesFeatureClassCB.setObjectName("geonamesFeatureClassCB")
        self.gridLayout_2.addWidget(self.geonamesFeatureClassCB, 2, 0, 1, 1)
        self.geonamesFeatureClassLE = QtWidgets.QLineEdit(self.geonamesTab)
        self.geonamesFeatureClassLE.setObjectName("geonamesFeatureClassLE")
        self.gridLayout_2.addWidget(self.geonamesFeatureClassLE, 2, 3, 1, 1)
        self.geonamesCountryCodeCB = QtWidgets.QCheckBox(self.geonamesTab)
        self.geonamesCountryCodeCB.setText("")
        self.geonamesCountryCodeCB.setObjectName("geonamesCountryCodeCB")
        self.gridLayout_2.addWidget(self.geonamesCountryCodeCB, 1, 0, 1, 1)
        self.geonamesCountryCodeLE = QtWidgets.QLineEdit(self.geonamesTab)
        self.geonamesCountryCodeLE.setObjectName("geonamesCountryCodeLE")
        self.gridLayout_2.addWidget(self.geonamesCountryCodeLE, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.geonamesTab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 1, 1, 1)
        self.geonamesLimitLE = QtWidgets.QLineEdit(self.geonamesTab)
        self.geonamesLimitLE.setObjectName("geonamesLimitLE")
        self.gridLayout_2.addWidget(self.geonamesLimitLE, 3, 3, 1, 1)
        self.queryServicesTW.addTab(self.geonamesTab, "")
        self.directInputTab = QtWidgets.QWidget()
        self.directInputTab.setObjectName("directInputTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.directInputTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.directInputNameLE = QtWidgets.QLineEdit(self.directInputTab)
        self.directInputNameLE.setObjectName("directInputNameLE")
        self.gridLayout_3.addWidget(self.directInputNameLE, 0, 1, 1, 1)
        self.directInputLatLE = QtWidgets.QLineEdit(self.directInputTab)
        self.directInputLatLE.setObjectName("directInputLatLE")
        self.gridLayout_3.addWidget(self.directInputLatLE, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.directInputTab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.directInputTab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.directInputTab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.directInputLonLE = QtWidgets.QLineEdit(self.directInputTab)
        self.directInputLonLE.setObjectName("directInputLonLE")
        self.gridLayout_3.addWidget(self.directInputLonLE, 2, 1, 1, 1)
        self.queryServicesTW.addTab(self.directInputTab, "")
        self.verticalLayout_3.addWidget(self.queryServicesTW)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runQueryPB = QtWidgets.QPushButton(self.groupBox_2)
        self.runQueryPB.setObjectName("runQueryPB")
        self.horizontalLayout.addWidget(self.runQueryPB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.resultsListAndMapHBL = QtWidgets.QHBoxLayout()
        self.resultsListAndMapHBL.setObjectName("resultsListAndMapHBL")
        self.resultsLV = QtWidgets.QListView(self.groupBox_3)
        self.resultsLV.setObjectName("resultsLV")
        self.resultsListAndMapHBL.addWidget(self.resultsLV)
        self.verticalLayout_4.addLayout(self.resultsListAndMapHBL)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.resultsClearSelectionPB = QtWidgets.QPushButton(self.groupBox_3)
        self.resultsClearSelectionPB.setObjectName("resultsClearSelectionPB")
        self.horizontalLayout_3.addWidget(self.resultsClearSelectionPB)
        self.resultsSelectAllPB = QtWidgets.QPushButton(self.groupBox_3)
        self.resultsSelectAllPB.setObjectName("resultsSelectAllPB")
        self.horizontalLayout_3.addWidget(self.resultsSelectAllPB)
        self.resultsInvertSelectionPB = QtWidgets.QPushButton(self.groupBox_3)
        self.resultsInvertSelectionPB.setObjectName("resultsInvertSelectionPB")
        self.horizontalLayout_3.addWidget(self.resultsInvertSelectionPB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.addFeaturesTW = QtWidgets.QTabWidget(self.groupBox_4)
        self.addFeaturesTW.setObjectName("addFeaturesTW")
        self.shapefileTab = QtWidgets.QWidget()
        self.shapefileTab.setObjectName("shapefileTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.shapefileTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.shapefileFieldCB = QtWidgets.QComboBox(self.shapefileTab)
        self.shapefileFieldCB.setObjectName("shapefileFieldCB")
        self.horizontalLayout_5.addWidget(self.shapefileFieldCB)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.shapefileTab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.shapefileTab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 2, 0, 1, 1)
        self.shapefileCreateNewPB = QtWidgets.QPushButton(self.shapefileTab)
        self.shapefileCreateNewPB.setObjectName("shapefileCreateNewPB")
        self.gridLayout_4.addWidget(self.shapefileCreateNewPB, 0, 0, 1, 1)
        self.shapefileAddLE = QtWidgets.QLineEdit(self.shapefileTab)
        self.shapefileAddLE.setObjectName("shapefileAddLE")
        self.gridLayout_4.addWidget(self.shapefileAddLE, 1, 1, 1, 1)
        self.shapefileOpenFileTB = QtWidgets.QToolButton(self.shapefileTab)
        self.shapefileOpenFileTB.setObjectName("shapefileOpenFileTB")
        self.gridLayout_4.addWidget(self.shapefileOpenFileTB, 1, 2, 1, 1)
        self.addFeaturesTW.addTab(self.shapefileTab, "")
        self.layerTab = QtWidgets.QWidget()
        self.layerTab.setObjectName("layerTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layerTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_12 = QtWidgets.QLabel(self.layerTab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layerTab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)
        self.layerPickLayerCB = QtWidgets.QComboBox(self.layerTab)
        self.layerPickLayerCB.setObjectName("layerPickLayerCB")
        self.gridLayout_5.addWidget(self.layerPickLayerCB, 0, 1, 1, 1)
        self.layerFieldCB = QtWidgets.QComboBox(self.layerTab)
        self.layerFieldCB.setObjectName("layerFieldCB")
        self.gridLayout_5.addWidget(self.layerFieldCB, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 1, 3, 1, 1)
        self.layerRefreshTB = QtWidgets.QToolButton(self.layerTab)
        self.layerRefreshTB.setObjectName("layerRefreshTB")
        self.gridLayout_5.addWidget(self.layerRefreshTB, 0, 2, 1, 1)
        self.addFeaturesTW.addTab(self.layerTab, "")
        self.csvTab = QtWidgets.QWidget()
        self.csvTab.setObjectName("csvTab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.csvTab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.csvTab)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.csvAddToFileLE = QtWidgets.QLineEdit(self.csvTab)
        self.csvAddToFileLE.setObjectName("csvAddToFileLE")
        self.horizontalLayout_6.addWidget(self.csvAddToFileLE)
        self.csvOpenFileTB = QtWidgets.QToolButton(self.csvTab)
        self.csvOpenFileTB.setObjectName("csvOpenFileTB")
        self.horizontalLayout_6.addWidget(self.csvOpenFileTB)
        self.addFeaturesTW.addTab(self.csvTab, "")
        self.verticalLayout_5.addWidget(self.addFeaturesTW)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addFeatureAddPB = QtWidgets.QPushButton(self.groupBox_4)
        self.addFeatureAddPB.setObjectName("addFeatureAddPB")
        self.horizontalLayout_4.addWidget(self.addFeatureAddPB)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 605, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.queryServicesTW.setCurrentIndex(1)
        self.addFeaturesTW.setCurrentIndex(1)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Locations From Web Services"))
        self.groupBox.setToolTip(_translate("MainWindow", "Enter name to search for here."))
        self.groupBox.setTitle(_translate("MainWindow", "Query term"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Service"))
        self.label.setText(_translate("MainWindow", "Country code:"))
        self.label_2.setText(_translate("MainWindow", "Limit:"))
        self.nominatimLimitLE.setText(_translate("MainWindow", "10"))
        self.queryServicesTW.setTabText(self.queryServicesTW.indexOf(self.nominatimTab), _translate("MainWindow", "OSM Nominatim"))
        self.label_4.setText(_translate("MainWindow", "Country code:"))
        self.label_3.setText(_translate("MainWindow", "GeoNames user name:"))
        self.label_5.setText(_translate("MainWindow", "Feature class:"))
        self.label_6.setText(_translate("MainWindow", "Limit:"))
        self.geonamesLimitLE.setText(_translate("MainWindow", "10"))
        self.queryServicesTW.setTabText(self.queryServicesTW.indexOf(self.geonamesTab), _translate("MainWindow", "GeoNames"))
        self.label_8.setText(_translate("MainWindow", "Latitude:"))
        self.label_7.setText(_translate("MainWindow", "Name:"))
        self.label_9.setText(_translate("MainWindow", "Longitude:"))
        self.queryServicesTW.setTabText(self.queryServicesTW.indexOf(self.directInputTab), _translate("MainWindow", "Direct input"))
        self.runQueryPB.setText(_translate("MainWindow", "Run query"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Results"))
        self.resultsClearSelectionPB.setText(_translate("MainWindow", "Clear selection"))
        self.resultsSelectAllPB.setText(_translate("MainWindow", "Select all"))
        self.resultsInvertSelectionPB.setText(_translate("MainWindow", "Invert selection"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Add features"))
        self.label_10.setText(_translate("MainWindow", "Add to shapefile:"))
        self.label_11.setText(_translate("MainWindow", "Field to store name:"))
        self.shapefileCreateNewPB.setText(_translate("MainWindow", "Create new shapefile..."))
        self.shapefileOpenFileTB.setText(_translate("MainWindow", "..."))
        self.addFeaturesTW.setTabText(self.addFeaturesTW.indexOf(self.shapefileTab), _translate("MainWindow", "Shapefile"))
        self.label_12.setText(_translate("MainWindow", "Pick layer:"))
        self.label_13.setText(_translate("MainWindow", "Field to store name:"))
        self.layerRefreshTB.setText(_translate("MainWindow", "..."))
        self.addFeaturesTW.setTabText(self.addFeaturesTW.indexOf(self.layerTab), _translate("MainWindow", "Layer"))
        self.label_14.setText(_translate("MainWindow", "Add to file:"))
        self.csvOpenFileTB.setText(_translate("MainWindow", "..."))
        self.addFeaturesTW.setTabText(self.addFeaturesTW.indexOf(self.csvTab), _translate("MainWindow", "CSV"))
        self.addFeatureAddPB.setText(_translate("MainWindow", "Add"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

