colnames(state.x77)
head(state.x77[,"Income"])
par(oma = c(5, 0, 0, 0), las = 2) 
plot(state.division,state.x77[,"Income"])

par(mfrow = c(2, 2), mar = rep(4, 4))
hist(rnorm(30,mean=4,sd=2))
plot(dexp(5),type = "l")
boxplot(rgamma(30,3,scale=2))
qqnorm(rchisq(30,df=3))
