# Imports ...
from ipywidgets import Label, FloatSlider, FloatText, BoundedIntText, Button, Output, VBox, HBox

import scipy.stats as stats
import numpy as np

# Helpder functions to calculate the confidence intervals ...

# IPython widget controls for confidence intervals of normal and binomial distributions ...

# Button click event handlers ...
